service: serverless-react
provider:
  name: aws
  region: eu-west-1
  runtime: nodejs12.x

plugins:
  - serverless-export-outputs

custom:
  exportOutputs: # if not provided, all outputs are exported
    - WebSiteBucket

functions:

resources:
  # S3
  - ${file(resources/s3-bucket.yml)}
  # CloudFront
  - ${file(resources/cloudfront.yml)}
