name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn --frozen-lockfile
      - run: yarn build --if-present
      - run: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - run: unzip awscliv2.zip
      - run: sudo yarn global add serverless
      - run: sudo ./aws/install
      - run: aws --version
      - run: serverless deploy -s dev
      - run: chmod +x ./scripts/deploy.sh
      - run: BUCKET=$(./scripts/deploy.sh)
      - run: aws s3 sync build/ "s3://${BUCKET}" --acl public-read
