name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
        name: Checkout code

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          node-version: ${{ matrix.node-version }}
        run: yarn --frozen-lockfile
        run: yarn build --if-present
        run: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        run: unzip awscliv2.zip
        run: sudo ./aws/install
        run: aws --version
        run: sudo yarn global add serverless
        run: serverless deploy -s dev
        run: chmod +x ./scripts/deploy.sh
        run: BUCKET=$(./scripts/deploy.sh)
        run: aws s3 sync build/ "s3://${BUCKET}" --acl public-read
